# Generated by Django 4.2.4 on 2023-11-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BodyLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("neck", "Neck"),
                            ("chest", "Chest"),
                            ("torso", "Torso"),
                            ("back", "Back"),
                            ("arm", "Arm"),
                            ("hand", "Hand"),
                            ("hip", "Hip"),
                            ("glutes", "Glutes"),
                            ("pelvic", "Pelvic"),
                            ("leg", "Leg"),
                            ("foot", "Foot"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BodyLocationPiercing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Belly Piercing", "Belly Piercing"),
                            ("Ear Area Piercing", "Ear Area Piercing"),
                            ("Facial Area Piercing", "Facial Area Piercing"),
                            ("Jewelry Swap Piercing", "Jewelry Swap Piercing"),
                            ("Nipple Piercing", "Nipple Piercing"),
                            ("Nose Area Piercing", "Nose Area Piercing"),
                            ("Oral Area Piercing", "Oral Area Piercing"),
                            ("Surface Piercing", "Surface Piercing"),
                            ("Vaginal Area Piercing", "Vaginal Area Piercing"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Face",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Forehead", models.BooleanField(default=False)),
                ("Temple", models.BooleanField(default=False)),
                ("Eye_Brow", models.BooleanField(default=False)),
                ("Eyelid", models.BooleanField(default=False)),
                ("Nose", models.BooleanField(default=False)),
                ("Cheeks", models.BooleanField(default=False)),
                ("Lip", models.BooleanField(default=False)),
                ("Jaw", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Head",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Face", models.BooleanField(default=False)),
                ("Scalp", models.BooleanField(default=False)),
                ("Ear", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left_Leg", models.BooleanField(default=False)),
                ("Left_Full_Sleeve", models.BooleanField(default=False)),
                (
                    "Left_Full_Sleeve_Part",
                    models.CharField(
                        blank=True,
                        choices=[("lower", "Lower"), ("upper", "Upper")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("Left_Half_Sleeve", models.BooleanField(default=False)),
                ("Right_Leg", models.BooleanField(default=False)),
                ("Full_Right_Leg", models.BooleanField(default=False)),
                (
                    "Right_Full_Sleeve_Part",
                    models.CharField(
                        blank=True,
                        choices=[("lower", "Lower"), ("upper", "Upper")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("Full_Left_Half_Sleeve", models.BooleanField(default=False)),
                (
                    "Left_Half_Sleeve_Part",
                    models.CharField(
                        blank=True,
                        choices=[("lower", "Lower"), ("upper", "Upper")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Neck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_Chest", models.BooleanField(default=False)),
                ("Left_side", models.BooleanField(default=False)),
                ("Right_side", models.BooleanField(default=False)),
                ("Center", models.BooleanField(default=False)),
                ("Collarbone", models.BooleanField(default=False)),
                ("Nipple", models.BooleanField(default=False)),
                ("Under_chest", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("tattoo", "Tattoo"),
                            ("piercing", "Piercing"),
                            ("tooth_gems", "Tooth Gems"),
                            ("tattoo_removal", "Tattoo Removal"),
                            ("permanent_makeup", "Permanent Makeup"),
                            ("scalp_micro_pigmentation", "Scalp Micro-Pigmentation"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VaginalAreaPiercing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("christina", models.BooleanField(default=False)),
                ("vertical_hood", models.BooleanField(default=False)),
                ("horizontal_hood", models.BooleanField(default=False)),
                ("inner_labia", models.BooleanField(default=False)),
                ("outer_labia", models.BooleanField(default=False)),
                ("fourchette", models.BooleanField(default=False)),
                ("hymen", models.BooleanField(default=False)),
                ("isabella", models.BooleanField(default=False)),
                ("princess_albertina", models.BooleanField(default=False)),
                ("triangle", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocationpiercing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                (
                    "service_categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="UserModel.servicecategories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Under_chest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.neck"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Torso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_Torso", models.BooleanField(default=False)),
                ("Left_Ribs", models.BooleanField(default=False)),
                ("Right_Ribs", models.BooleanField(default=False)),
                ("Stomach", models.BooleanField(default=False)),
                ("Belly_Button", models.BooleanField(default=False)),
                ("TummyTuck", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thigh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Inner", models.BooleanField(default=False)),
                ("Outer", models.BooleanField(default=False)),
                ("Front", models.BooleanField(default=False)),
                ("Back", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.leg"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Temple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.face"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TattooRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                (
                    "Parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.tattooremoval",
                    ),
                ),
                (
                    "body_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.servicecategories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tattoo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                (
                    "Parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="UserModel.tattoo",
                    ),
                ),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.servicecategories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurfacePiercing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arm", models.BooleanField(default=False)),
                ("back", models.BooleanField(default=False)),
                ("chest", models.BooleanField(default=False)),
                ("face", models.BooleanField(default=False)),
                ("finger", models.BooleanField(default=False)),
                ("foot", models.BooleanField(default=False)),
                ("hand", models.BooleanField(default=False)),
                ("hip", models.BooleanField(default=False)),
                ("leg", models.BooleanField(default=False)),
                ("neck", models.BooleanField(default=False)),
                ("pelvic", models.BooleanField(default=False)),
                ("ribs", models.BooleanField(default=False)),
                ("shoulder", models.BooleanField(default=False)),
                ("stomach", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocationpiercing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image_file", models.ImageField(upload_to="images/")),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.servicecategories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scalp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scalp_parts",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("back", "Back"),
                            ("left", "Left"),
                            ("full", "Full"),
                        ],
                        default="full",
                        max_length=10,
                    ),
                ),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.head"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermanentMakeUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EyeBrows", models.BooleanField(default=False)),
                ("Eyeliner", models.BooleanField(default=False)),
                ("Lips", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.servicecategories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pelvic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Top", models.BooleanField(default=False)),
                ("Middle", models.BooleanField(default=False)),
                ("Bottom", models.BooleanField(default=False)),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                ("Full", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OralAreaPiercing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("straight_bar_tongue", models.BooleanField(default=False)),
                ("snake_eye_tongue", models.BooleanField(default=False)),
                ("snake_bite_lip", models.BooleanField(default=False)),
                ("tongue_web", models.BooleanField(default=False)),
                ("smiley", models.BooleanField(default=False)),
                ("monroe", models.BooleanField(default=False)),
                ("medusa", models.BooleanField(default=False)),
                ("madonna", models.BooleanField(default=False)),
                ("dimples", models.BooleanField(default=False)),
                ("ashley", models.BooleanField(default=False)),
                ("angel_bites", models.BooleanField(default=False)),
                ("canine_bites", models.BooleanField(default=False)),
                ("cyber_bites", models.BooleanField(default=False)),
                ("dahlia", models.BooleanField(default=False)),
                ("dolphin_bites", models.BooleanField(default=False)),
                ("frowney", models.BooleanField(default=False)),
                ("gum", models.BooleanField(default=False)),
                ("horizontal_lip", models.BooleanField(default=False)),
                ("jestrum", models.BooleanField(default=False)),
                ("multi_tongue", models.BooleanField(default=False)),
                ("shark_bites", models.BooleanField(default=False)),
                ("spider_bites", models.BooleanField(default=False)),
                ("vampire", models.BooleanField(default=False)),
                ("venom", models.BooleanField(default=False)),
                ("vertical_labret", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocationpiercing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoseAreaPiercing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nostril", models.BooleanField(default=False)),
                ("Septum", models.BooleanField(default=False)),
                ("Austin_bar", models.BooleanField(default=False)),
                ("Erl", models.BooleanField(default=False)),
                ("High_nostril", models.BooleanField(default=False)),
                ("Nostril_nasallang", models.BooleanField(default=False)),
                ("Rhino", models.BooleanField(default=False)),
                ("Septril", models.BooleanField(default=False)),
                ("Third_eye", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocationpiercing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.face"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NipplePiercing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nipple", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocationpiercing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nipple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.neck"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LowerLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Inner", models.BooleanField(default=False)),
                ("Outer", models.BooleanField(default=False)),
                ("Front", models.BooleanField(default=False)),
                ("Back", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.leg"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Upper_Lip", models.BooleanField(default=False)),
                ("Lower_Lip", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.face"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Knee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Knee", models.BooleanField(default=False)),
                ("Front", models.BooleanField(default=False)),
                ("Back", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.leg"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JewelrySwapPiercing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nose_area", models.BooleanField(default=False)),
                ("Ear_area", models.BooleanField(default=False)),
                ("Belly", models.BooleanField(default=False)),
                ("Oral_area", models.BooleanField(default=False)),
                ("Facial_area", models.BooleanField(default=False)),
                ("Nipple", models.BooleanField(default=False)),
                ("Surface", models.BooleanField(default=False)),
                ("Vaginal_area", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocationpiercing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                ("Chin", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.face"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                ("Left_Top", models.BooleanField(default=False)),
                ("Left_Palm", models.BooleanField(default=False)),
                ("Left_Side", models.BooleanField(default=False)),
                ("Left_Fingers", models.BooleanField(default=False)),
                ("Right_Top", models.BooleanField(default=False)),
                ("Right_Palm", models.BooleanField(default=False)),
                ("Right_Side", models.BooleanField(default=False)),
                ("Right_Fingers", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Glutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Forehead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                ("center", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.face"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Foot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Left_Top", models.BooleanField(default=False)),
                ("Left_side", models.BooleanField(default=False)),
                ("Left_Toes", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                ("Right_Top", models.BooleanField(default=False)),
                ("Right_side", models.BooleanField(default=False)),
                ("Right_Toes", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacialAreaPiercing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Cheek", models.BooleanField(default=False)),
                ("Eyebrow", models.BooleanField(default=False)),
                ("Sideburn", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocationpiercing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="face",
            name="body_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="UserModel.head"
            ),
        ),
        migrations.CreateModel(
            name="Eyelid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.face"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Eye_Brow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.face"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EarAreaPiercing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Regular_earlobe", models.BooleanField(default=False)),
                ("Upper_earlobe", models.BooleanField(default=False)),
                ("Helix", models.BooleanField(default=False)),
                ("Industrial", models.BooleanField(default=False)),
                ("Tragus", models.BooleanField(default=False)),
                ("Rook", models.BooleanField(default=False)),
                ("Conch", models.BooleanField(default=False)),
                ("Daith", models.BooleanField(default=False)),
                ("Snug", models.BooleanField(default=False)),
                ("Forward_helix", models.BooleanField(default=False)),
                ("Anti_helix", models.BooleanField(default=False)),
                ("Anti_tragus", models.BooleanField(default=False)),
                ("Auricle", models.BooleanField(default=False)),
                ("Axternal_auditory_meatus", models.BooleanField(default=False)),
                ("Transverse_lobe", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocationpiercing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Right_Ear", models.BooleanField(default=False)),
                (
                    "right_ear_parts",
                    models.CharField(
                        choices=[
                            ("behind", "Behind"),
                            ("inner", "Inner"),
                            ("lobe", "Lobe"),
                        ],
                        default="lobe",
                        max_length=10,
                    ),
                ),
                ("Left_Ear", models.BooleanField(default=False)),
                (
                    "left_ear_parts",
                    models.CharField(
                        choices=[
                            ("behind", "Behind"),
                            ("inner", "Inner"),
                            ("lobe", "Lobe"),
                        ],
                        default="lobe",
                        max_length=10,
                    ),
                ),
                (
                    "Body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.head"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cheeks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left", models.BooleanField(default=False)),
                ("Right", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.face"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bodylocationpiercing",
            name="body_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="UserModel.servicecategories",
            ),
        ),
        migrations.AddField(
            model_name="bodylocation",
            name="service_categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="UserModel.servicecategories",
            ),
        ),
        migrations.CreateModel(
            name="BellyPiercing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Belly", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocationpiercing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Back",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_BackPiece", models.BooleanField(default=False)),
                ("Right_Shoulder", models.BooleanField(default=False)),
                ("Left_Shoulder", models.BooleanField(default=False)),
                ("Spine", models.BooleanField(default=False)),
                ("Lower_Back", models.BooleanField(default=False)),
                ("Other", models.BooleanField(default=False)),
                ("Other_explaination", models.TextField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Arm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Left_Arm", models.BooleanField(default=False)),
                (
                    "left_arm_parts",
                    models.CharField(
                        choices=[
                            ("half shoulder", "Half Sleeve"),
                            ("shoulder", "Shoulder"),
                            ("armpit", "ArmPit"),
                            ("upper armpit inner", "Upper ArmPit - Inner"),
                            ("upper armpit outer", "Upper ArmPit - Outer"),
                            ("upper armpit front", "Upper ArmPit - Front"),
                            ("upper armpit back", "Upper ArmPit - Back"),
                            ("elbow", "Elbow-Inner"),
                            ("elbow", "Elbow-Outer"),
                            ("forearm", "Forearm-Inner"),
                            ("forearm", "Forearm-Outer"),
                            ("forearm", "Forearm-Side"),
                            ("wrist", "Wrist-Inner"),
                            ("wrist", "Wrist-Outer"),
                            ("wrist", "Wrist-Side"),
                        ],
                        default="ArmPit",
                        max_length=20,
                    ),
                ),
                ("Right_Arm", models.BooleanField(default=False)),
                (
                    "Right_arm_parts",
                    models.CharField(
                        choices=[
                            ("half shoulder", "Half Sleeve"),
                            ("shoulder", "Shoulder"),
                            ("armpit", "ArmPit"),
                            ("upper armpit inner", "Upper ArmPit - Inner"),
                            ("upper armpit outer", "Upper ArmPit - Outer"),
                            ("upper armpit front", "Upper ArmPit - Front"),
                            ("upper armpit back", "Upper ArmPit - Back"),
                            ("elbow", "Elbow-Inner"),
                            ("elbow", "Elbow-Outer"),
                            ("forearm", "Forearm-Inner"),
                            ("forearm", "Forearm-Outer"),
                            ("forearm", "Forearm-Side"),
                            ("wrist", "Wrist-Inner"),
                            ("wrist", "Wrist-Outer"),
                            ("wrist", "Wrist-Side"),
                        ],
                        default="ArmPit",
                        max_length=20,
                    ),
                ),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ankle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full", models.BooleanField(default=False)),
                ("Inner", models.BooleanField(default=False)),
                ("Outer", models.BooleanField(default=False)),
                ("Front", models.BooleanField(default=False)),
                ("Back", models.BooleanField(default=False)),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserModel.leg"
                    ),
                ),
            ],
        ),
    ]
