# Generated by Django 4.2.4 on 2023-11-08 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserModel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToothGems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("ToothGems_Image", models.ImageField(upload_to="")),
                (
                    "body_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.servicecategories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToothGemMedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("influence_alcohol_drugs", models.BooleanField(default=False)),
                ("allergies", models.BooleanField(default=False)),
                ("medical_skin_conditions", models.BooleanField(default=False)),
                ("communicable_diseases", models.BooleanField(default=False)),
                ("health_conditions", models.BooleanField(default=False)),
                ("sensitive_teeth", models.BooleanField(default=False)),
                ("synthetic_teeth", models.BooleanField(default=False)),
                (
                    "service_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.toothgems",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TattooRemovalMedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tattoo_age", models.PositiveIntegerField()),
                ("adverse_reactions", models.BooleanField(default=False)),
                ("additional_treatment", models.BooleanField(default=False)),
                ("previous_removal_sessions", models.BooleanField(default=False)),
                ("removal_treatment_type", models.CharField(max_length=255)),
                ("total_sessions", models.PositiveIntegerField()),
                ("last_session_date", models.DateField()),
                ("pregnant_nursing", models.BooleanField(default=False)),
                ("hemophiliac_meds", models.BooleanField(default=False)),
                ("medical_skin_conditions", models.CharField(max_length=255)),
                ("communicable_diseases", models.CharField(max_length=255)),
                ("influence_alcohol_drugs", models.BooleanField(default=False)),
                ("allergies", models.CharField(max_length=255)),
                ("health_conditions", models.CharField(max_length=255)),
                ("accutane_usage", models.BooleanField(default=False)),
                ("anesthetic_problems", models.BooleanField(default=False)),
                ("medical_implants", models.BooleanField(default=False)),
                ("asthma", models.BooleanField(default=False)),
                ("autoimmune_disorder", models.BooleanField(default=False)),
                ("faint_dizzy", models.BooleanField(default=False)),
                ("healing_problems", models.BooleanField(default=False)),
                ("herbal_supplements_today", models.BooleanField(default=False)),
                ("hyper_hypo_pigment", models.BooleanField(default=False)),
                ("pacemaker", models.BooleanField(default=False)),
                ("radiation_chemo_treatment", models.BooleanField(default=False)),
                ("seizure_condition", models.BooleanField(default=False)),
                ("skin_cancer", models.BooleanField(default=False)),
                ("smoker", models.BooleanField(default=False)),
                ("tanning_bed_usage", models.BooleanField(default=False)),
                ("sunburn_easily", models.BooleanField(default=False)),
                ("vitiligo", models.BooleanField(default=False)),
                (
                    "service_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.tattooremoval",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TattooMedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tattoo_before", models.BooleanField(default=False)),
                ("pregnant_nursing", models.BooleanField(default=False)),
                ("hemophilics_med", models.BooleanField(default=False)),
                ("medical_skin_condition", models.BooleanField(default=False)),
                ("communicable_disease", models.BooleanField(default=False)),
                ("influence_alcohol_drugs", models.BooleanField(default=False)),
                ("allergies", models.BooleanField(default=False)),
                ("health_conditions", models.BooleanField(default=False)),
                (
                    "Selected_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="UserModel.tattoo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMPMedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tattoo_before", models.BooleanField(default=False)),
                ("pregnant_nursing", models.BooleanField(default=False)),
                ("hemophilics_med", models.BooleanField(default=False)),
                ("medical_skin_condition", models.BooleanField(default=False)),
                ("communicable_disease", models.BooleanField(default=False)),
                ("influence_alcohol_drugs", models.BooleanField(default=False)),
                ("allergies", models.BooleanField(default=False)),
                ("health_conditions", models.BooleanField(default=False)),
                (
                    "Selected_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="UserModel.smp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PiercingMedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pierced_before", models.BooleanField(default=False)),
                ("pregnant_nursing", models.BooleanField(default=False)),
                ("hemophiliac_meds", models.BooleanField(default=False)),
                ("medical_skin_conditions", models.BooleanField(default=False)),
                ("communicable_diseases", models.BooleanField(default=False)),
                ("influence_alcohol_drugs", models.BooleanField(default=False)),
                ("allergies", models.BooleanField(default=False)),
                ("health_conditions", models.BooleanField(default=False)),
                (
                    "service_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.bodylocationpiercing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermanentMakeUpMedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tattoo_before", models.BooleanField(default=False)),
                ("pregnant_nursing", models.BooleanField(default=False)),
                ("hemophilics_med", models.BooleanField(default=False)),
                ("medical_skin_condition", models.BooleanField(default=False)),
                ("communicable_disease", models.BooleanField(default=False)),
                ("influence_alcohol_drugs", models.BooleanField(default=False)),
                ("allergies", models.BooleanField(default=False)),
                ("health_conditions", models.BooleanField(default=False)),
                (
                    "Selected_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="UserModel.permanentmakeup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=16)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                (
                    "Selected_services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="UserModel.servicecategories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Doctor_name", models.CharField(max_length=30)),
                ("Docotr_phone", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                (
                    "Emergency_Contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_info",
                        to="UserModel.emergencycontact",
                    ),
                ),
            ],
        ),
    ]
