# Generated by Django 4.2.7 on 2023-11-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserModel", "0004_tattowaiver_body_location_toothgemswaiver_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaiverAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "agreement_text",
                    models.TextField(
                        help_text="Copy and paste the entire agreement text here.",
                        verbose_name="Agreement Text",
                    ),
                ),
                (
                    "initials",
                    models.BooleanField(default=False, verbose_name="Initials"),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="waiver_signatures/",
                        verbose_name="Signature",
                    ),
                ),
                (
                    "body_location",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.servicecategories",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waiver Agreement",
                "verbose_name_plural": "Waiver Agreements",
            },
        ),
        migrations.CreateModel(
            name="TermsOfService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserModel.servicecategories",
                    ),
                ),
            ],
        ),
    ]
