# Generated by Django 4.2.4 on 2023-10-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accountapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_selected_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountapp.servicecategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="select_services",
                        to="accountapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SharedMedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tattoo_before", models.BooleanField(default=False)),
                ("pregnant_nursuring", models.BooleanField(default=False)),
                ("Hemophiliac_attention", models.BooleanField(default=False)),
                ("medical_or_skin_condition", models.BooleanField(default=False)),
                ("Communicable_disease", models.BooleanField(default=False)),
                ("influence_drug_alcohol", models.BooleanField(default=False)),
                ("heart_condition", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Medical_Record",
                        to="accountapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emergency_Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("State", models.CharField(blank=True, max_length=150)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Emergency_Contact",
                        to="accountapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("state", models.CharField(blank=True, max_length=150)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Doctor_Informations",
                        to="accountapp.user",
                    ),
                ),
            ],
        ),
    ]
