# Generated by Django 4.2.6 on 2023-10-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accountapp", "0002_user_selected_category_sharedmedicalrecord_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctorinfo",
            old_name="city",
            new_name="City",
        ),
        migrations.RenameField(
            model_name="doctorinfo",
            old_name="name",
            new_name="Name",
        ),
        migrations.RenameField(
            model_name="doctorinfo",
            old_name="phone_number",
            new_name="Phone_number",
        ),
        migrations.RenameField(
            model_name="doctorinfo",
            old_name="state",
            new_name="State",
        ),
        migrations.RenameField(
            model_name="emergency_contact",
            old_name="city",
            new_name="City",
        ),
        migrations.RenameField(
            model_name="emergency_contact",
            old_name="name",
            new_name="Name",
        ),
        migrations.RenameField(
            model_name="emergency_contact",
            old_name="phone_number",
            new_name="Phone_number",
        ),
        migrations.RenameField(
            model_name="sharedmedicalrecord",
            old_name="heart_condition",
            new_name="Heart_disease",
        ),
        migrations.RenameField(
            model_name="sharedmedicalrecord",
            old_name="influence_drug_alcohol",
            new_name="Influence_drug_alcohol",
        ),
        migrations.RenameField(
            model_name="sharedmedicalrecord",
            old_name="medical_or_skin_condition",
            new_name="Medical_or_skin_condition",
        ),
        migrations.RenameField(
            model_name="sharedmedicalrecord",
            old_name="pregnant_nursuring",
            new_name="Pregnanancy_conditions",
        ),
        migrations.RenameField(
            model_name="sharedmedicalrecord",
            old_name="tattoo_before",
            new_name="Tattoo_before",
        ),
        migrations.RemoveField(
            model_name="servicecategory",
            name="category",
        ),
        migrations.CreateModel(
            name="SharedWaiverAndRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_1", models.BooleanField(default=False)),
                ("page_2", models.BooleanField(default=False)),
                ("page_3", models.BooleanField(default=False)),
                ("page_4", models.BooleanField(default=False)),
                ("page_5", models.BooleanField(default=False)),
                ("page_6", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiver_and_release",
                        to="accountapp.user",
                    ),
                ),
            ],
        ),
    ]
