# Generated by Django 4.2.6 on 2023-10-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountapp", "0004_toothgemwaiverandrelease_toothgemmedicalrecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdharmlessagreement",
            name="client_photo",
            field=models.ImageField(blank=True, upload_to="client_photos/"),
        ),
    ]
