# Generated by Django 4.2.6 on 2023-10-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accountapp", "0005_alter_holdharmlessagreement_client_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_minor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="minor_address",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="minor_city",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="minor_state",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="minor_zip",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name="ParentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_name", models.CharField(max_length=100)),
                ("parent_phone", models.CharField(max_length=15)),
                ("parent_address", models.CharField(max_length=150)),
                ("parent_city", models.CharField(max_length=150)),
                ("parent_state", models.CharField(max_length=150)),
                ("parent_zip", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountapp.user",
                    ),
                ),
            ],
        ),
    ]
